import { motion } from "framer-motion";
import { Copy, Download, FileCode, Layers, Box, Cpu, Database, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Architecture } from "./ArchitecturePanel";

interface RTLPanelProps {
  projectId: string;
  architecture: Architecture | null;
}

const RTLPanel = ({ projectId, architecture }: RTLPanelProps) => {
  if (!architecture) {
    return (
      <div className="h-full flex items-center justify-center text-muted-foreground">
        <div className="text-center">
          <Cpu className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <p className="text-lg mb-2">No architecture selected</p>
          <p className="text-sm">Select an architecture from the evaluation panel first</p>
        </div>
      </div>
    );
  }

  const rtlBlocks = {
    systolic_array: [
      { name: "systolic_pe_array", type: "Datapath", lines: 450, status: "ready" },
      { name: "weight_buffer", type: "Memory", lines: 180, status: "ready" },
      { name: "activation_fifo", type: "Memory", lines: 120, status: "ready" },
      { name: "mac_unit", type: "Compute", lines: 85, status: "ready" },
      { name: "accumulator_bank", type: "Datapath", lines: 200, status: "ready" },
      { name: "control_fsm", type: "Control", lines: 320, status: "needs_review" },
      { name: "axi4_master", type: "Interface", lines: 580, status: "ready" },
      { name: "clock_gate_ctrl", type: "Power", lines: 95, status: "ready" },
    ],
    npu_mesh: [
      { name: "mesh_router", type: "NoC", lines: 380, status: "ready" },
      { name: "npu_tile", type: "Compute", lines: 520, status: "ready" },
      { name: "local_memory", type: "Memory", lines: 240, status: "ready" },
      { name: "mesh_controller", type: "Control", lines: 410, status: "needs_review" },
      { name: "dma_engine", type: "Interface", lines: 350, status: "ready" },
      { name: "credit_manager", type: "Control", lines: 180, status: "ready" },
    ],
    vector_engine: [
      { name: "vector_alu", type: "Compute", lines: 620, status: "ready" },
      { name: "vector_register_file", type: "Memory", lines: 380, status: "ready" },
      { name: "lane_controller", type: "Control", lines: 290, status: "ready" },
      { name: "memory_unit", type: "Memory", lines: 450, status: "needs_review" },
      { name: "scatter_gather", type: "Datapath", lines: 320, status: "ready" },
    ],
    dataflow: [
      { name: "token_controller", type: "Control", lines: 480, status: "needs_review" },
      { name: "firing_unit", type: "Compute", lines: 350, status: "ready" },
      { name: "token_buffer", type: "Memory", lines: 200, status: "ready" },
      { name: "scheduler", type: "Control", lines: 550, status: "needs_review" },
      { name: "result_collector", type: "Datapath", lines: 280, status: "ready" },
    ],
    hybrid_simd: [
      { name: "simd_lane", type: "Compute", lines: 420, status: "ready" },
      { name: "tensor_core", type: "Compute", lines: 680, status: "ready" },
      { name: "mode_controller", type: "Control", lines: 380, status: "needs_review" },
      { name: "shared_memory", type: "Memory", lines: 290, status: "ready" },
      { name: "dispatch_unit", type: "Control", lines: 340, status: "ready" },
    ],
  };

  const blocks = rtlBlocks[architecture.id as keyof typeof rtlBlocks] || rtlBlocks.systolic_array;

  const getTypeColor = (type: string) => {
    switch (type) {
      case "Datapath": return "bg-primary/20 text-primary border-primary/30";
      case "Memory": return "bg-accent/20 text-accent-foreground border-accent/30";
      case "Compute": return "bg-success/20 text-success border-success/30";
      case "Control": return "bg-warning/20 text-warning border-warning/30";
      case "Interface": return "bg-secondary text-secondary-foreground border-secondary";
      case "Power": return "bg-muted text-muted-foreground border-muted";
      case "NoC": return "bg-primary/30 text-primary border-primary/40";
      default: return "bg-muted text-muted-foreground border-border";
    }
  };

  const sampleRTL = `// ${architecture.name} - Top Module
// Auto-generated by ForgeVeda RTL Agent
// Target: ${architecture.ppa.performance} TOPS @ ${architecture.ppa.power}W

module ${architecture.id}_top #(
  parameter DATA_WIDTH = 8,
  parameter NUM_PE     = 256,
  parameter DEPTH      = 16
)(
  input  logic                    clk,
  input  logic                    rst_n,
  input  logic [DATA_WIDTH-1:0]   data_in,
  input  logic                    valid_in,
  output logic [DATA_WIDTH*2-1:0] result,
  output logic                    valid_out
);

  // Internal signals
  logic [DATA_WIDTH-1:0] weight_buffer [0:DEPTH-1];
  logic [DATA_WIDTH*2-1:0] partial_sum;
  
  // Instantiate PE array
  genvar i;
  generate
    for (i = 0; i < NUM_PE; i++) begin : pe_inst
      processing_element #(
        .DATA_WIDTH(DATA_WIDTH)
      ) pe (
        .clk(clk),
        .rst_n(rst_n),
        .a_in(data_in),
        .b_in(weight_buffer[i % DEPTH]),
        .sum_in(partial_sum),
        .sum_out(partial_sum)
      );
    end
  endgenerate

endmodule`;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const exportRTL = () => {
    const blob = new Blob([sampleRTL], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${architecture.id}_top.sv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full p-6 overflow-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold mb-1">RTL Planning</h1>
          <p className="text-muted-foreground">
            Block hierarchy for {architecture.name}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="secondary" size="sm" className="gap-2" onClick={exportRTL}>
            <Download className="w-4 h-4" />
            Export RTL
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Block Hierarchy */}
        <div className="glass-panel p-6">
          <div className="flex items-center gap-2 mb-4">
            <Layers className="w-5 h-5 text-primary" />
            <h3 className="text-lg font-semibold">Block Hierarchy</h3>
          </div>
          <div className="space-y-3">
            {blocks.map((block, index) => (
              <motion.div
                key={block.name}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.05 }}
                className="flex items-center justify-between p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors cursor-pointer"
              >
                <div className="flex items-center gap-3">
                  <FileCode className="w-4 h-4 text-muted-foreground" />
                  <span className="font-mono text-sm">{block.name}.sv</span>
                  <span className={`px-2 py-0.5 rounded text-xs border ${getTypeColor(block.type)}`}>
                    {block.type}
                  </span>
                </div>
                <div className="flex items-center gap-4">
                  <span className="text-xs text-muted-foreground">{block.lines} lines</span>
                  <span className={`w-2 h-2 rounded-full ${block.status === "ready" ? "bg-success" : "bg-warning"}`} />
                </div>
              </motion.div>
            ))}
          </div>
          <div className="mt-4 pt-4 border-t border-border">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Total Lines of Code:</span>
              <span className="font-mono">{blocks.reduce((sum, b) => sum + b.lines, 0).toLocaleString()}</span>
            </div>
          </div>
        </div>

        {/* RTL Preview */}
        <div className="glass-panel p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Box className="w-5 h-5 text-primary" />
              <h3 className="text-lg font-semibold">RTL Preview</h3>
            </div>
            <Button variant="ghost" size="sm" className="gap-2" onClick={() => copyToClipboard(sampleRTL)}>
              <Copy className="w-4 h-4" />
              Copy
            </Button>
          </div>
          <div className="bg-background rounded-lg p-4 overflow-auto max-h-[400px]">
            <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
              {sampleRTL}
            </pre>
          </div>
        </div>
      </div>

      {/* Dependency Graph */}
      <div className="glass-panel p-6 mt-6">
        <div className="flex items-center gap-2 mb-4">
          <Database className="w-5 h-5 text-primary" />
          <h3 className="text-lg font-semibold">Module Dependencies</h3>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {blocks.slice(0, 4).map((block, index) => (
            <motion.div
              key={block.name}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3 + index * 0.1 }}
              className="flex items-center gap-2"
            >
              <div className="px-3 py-2 rounded-lg bg-muted/50 font-mono text-sm">
                {block.name}
              </div>
              {index < 3 && <ArrowRight className="w-4 h-4 text-muted-foreground" />}
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default RTLPanel;
