import { useState } from "react";
import { motion } from "framer-motion";
import { Copy, Download, CheckCircle2, AlertCircle, Clock, FileCode, Shield, Play } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Architecture } from "./ArchitecturePanel";
import { Progress } from "@/components/ui/progress";

interface VerificationPanelProps {
  projectId: string;
  architecture: Architecture | null;
}

const VerificationPanel = ({ projectId, architecture }: VerificationPanelProps) => {
  if (!architecture) {
    return (
      <div className="h-full flex items-center justify-center text-muted-foreground">
        <div className="text-center">
          <Shield className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <p className="text-lg mb-2">No architecture selected</p>
          <p className="text-sm">Select an architecture from the evaluation panel first</p>
        </div>
      </div>
    );
  }

  const [tests, setTests] = useState([
    { name: "async_reset_test", status: "pending", coverage: 0, cycles: 0 },
    { name: "fifo_overflow_test", status: "pending", coverage: 0, cycles: 0 },
    { name: "fifo_underflow_test", status: "pending", coverage: 0, cycles: 0 },
    { name: "bus_contention_test", status: "pending", coverage: 0, cycles: 0 },
    { name: "axi4_protocol_test", status: "pending", coverage: 0, cycles: 0 },
    { name: "power_gating_test", status: "pending", coverage: 0, cycles: 0 },
    { name: "corner_case_stress", status: "pending", coverage: 0, cycles: 0 },
  ]);

  const [isRunning, setIsRunning] = useState(false);

  // Simulation runner
  const runVerification = async () => {
    setIsRunning(true);

    // Reset all
    setTests(prev => prev.map(t => ({ ...t, status: "pending", coverage: 0, cycles: 0 })));

    for (let i = 0; i < tests.length; i++) {
      // Set current to running
      setTests(prev => {
        const copy = [...prev];
        copy[i].status = "running";
        return copy;
      });

      // Simulate random duration 500ms - 1500ms
      await new Promise(r => setTimeout(r, Math.random() * 1000 + 500));

      // Complete test
      setTests(prev => {
        const copy = [...prev];
        copy[i].status = "passed";
        copy[i].coverage = 85 + Math.random() * 15; // Random high coverage
        copy[i].cycles = Math.floor(Math.random() * 5000) + 1000;
        return copy;
      });
    }
    setIsRunning(false);
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "passed":
        return <CheckCircle2 className="w-4 h-4 text-success" />;
      case "running":
        return <Clock className="w-4 h-4 text-primary animate-spin" />;
      case "failed":
        return <AlertCircle className="w-4 h-4 text-destructive" />;
      default:
        return <Clock className="w-4 h-4 text-muted-foreground" />;
    }
  };

  const testbenchCode = `// SystemVerilog Testbench for ${architecture.name}
// Auto-generated by ForgeVeda Verification Agent
// Coverage Target: 98.5%

\`timescale 1ns/1ps

module ${architecture.id}_tb;

  // Clock and reset
  logic clk = 0;
  logic rst_n;
  
  // DUT signals
  logic [7:0]  data_in;
  logic        valid_in;
  logic [15:0] result;
  logic        valid_out;

  // Clock generation
  always #5 clk = ~clk;

  // DUT instantiation
  ${architecture.id}_top dut (
    .clk(clk),
    .rst_n(rst_n),
    .data_in(data_in),
    .valid_in(valid_in),
    .result(result),
    .valid_out(valid_out)
  );

  // Async reset test
  task automatic test_async_reset();
    \$display("[%0t] Starting async reset test", \$time);
    rst_n = 1;
    repeat(10) @(posedge clk);
    rst_n = 0;
    repeat(5) @(posedge clk);
    assert(result == 0) else \$error("Reset failed!");
    rst_n = 1;
    \$display("[%0t] Async reset test PASSED", \$time);
  endtask

  // FIFO overflow test
  task automatic test_fifo_overflow();
    \$display("[%0t] Starting FIFO overflow test", \$time);
    for (int i = 0; i < 100; i++) begin
      @(posedge clk);
      data_in = \$urandom();
      valid_in = 1;
    end
    valid_in = 0;
    \$display("[%0t] FIFO overflow test PASSED", \$time);
  endtask

  // Main test sequence
  initial begin
    \$display("=== ${architecture.name} Testbench ===");
    rst_n = 0;
    data_in = 0;
    valid_in = 0;
    
    #100;
    test_async_reset();
    test_fifo_overflow();
    
    #1000;
    \$display("=== All tests completed ===");
    \$finish;
  end

endmodule`;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const exportTestbench = () => {
    const blob = new Blob([testbenchCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${architecture.id}_tb.sv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const totalCoverage = tests.filter(t => t.status === "passed").reduce((sum, t) => sum + t.coverage, 0) /
    (tests.filter(t => t.status === "passed").length || 1);

  return (
    <div className="h-full p-6 overflow-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold mb-1">Verification</h1>
          <p className="text-muted-foreground">
            Test strategy for {architecture.name}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button
            variant="default"
            size="sm"
            className="gap-2"
            onClick={runVerification}
            disabled={isRunning}
          >
            {isRunning ? <Clock className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
            {isRunning ? "Verifying..." : "Run Verification"}
          </Button>
          <Button variant="secondary" size="sm" className="gap-2" onClick={exportTestbench}>
            <Download className="w-4 h-4" />
            Export Testbench
          </Button>
        </div>
      </div>

      {/* Coverage Overview */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="glass-panel p-4">
          <p className="text-sm text-muted-foreground mb-2">Overall Coverage</p>
          <div className="flex items-end gap-2">
            <span className="text-3xl font-semibold">{totalCoverage.toFixed(1)}%</span>
            <span className="text-success text-sm mb-1">Target: 98.5%</span>
          </div>
          <Progress value={totalCoverage} className="mt-2" />
        </div>
        <div className="glass-panel p-4">
          <p className="text-sm text-muted-foreground mb-2">Tests Passed</p>
          <div className="flex items-end gap-2">
            <span className="text-3xl font-semibold text-success">
              {tests.filter(t => t.status === "passed").length}
            </span>
            <span className="text-muted-foreground text-sm mb-1">/ {tests.length}</span>
          </div>
        </div>
        <div className="glass-panel p-4">
          <p className="text-sm text-muted-foreground mb-2">Simulation Cycles</p>
          <div className="flex items-end gap-2">
            <span className="text-3xl font-semibold font-mono">
              {tests.reduce((sum, t) => sum + t.cycles, 0).toLocaleString()}
            </span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Test Cases */}
        <div className="glass-panel p-6">
          <div className="flex items-center gap-2 mb-4">
            <Shield className="w-5 h-5 text-primary" />
            <h3 className="text-lg font-semibold">Test Cases</h3>
          </div>
          <div className="space-y-3">
            {tests.map((test, index) => (
              <motion.div
                key={test.name}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.05 }}
                className="flex items-center justify-between p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors"
              >
                <div className="flex items-center gap-3">
                  {getStatusIcon(test.status)}
                  <span className="font-mono text-sm">{test.name}</span>
                </div>
                <div className="flex items-center gap-4 text-sm">
                  {test.status === "passed" && (
                    <span className="text-muted-foreground">{test.coverage}%</span>
                  )}
                  {test.cycles > 0 && (
                    <span className="font-mono text-xs text-muted-foreground">
                      {test.cycles.toLocaleString()} cycles
                    </span>
                  )}
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Testbench Preview */}
        <div className="glass-panel p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <FileCode className="w-5 h-5 text-primary" />
              <h3 className="text-lg font-semibold">Testbench Preview</h3>
            </div>
            <Button variant="ghost" size="sm" className="gap-2" onClick={() => copyToClipboard(testbenchCode)}>
              <Copy className="w-4 h-4" />
              Copy
            </Button>
          </div>
          <div className="bg-background rounded-lg p-4 overflow-auto max-h-[400px]">
            <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
              {testbenchCode}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VerificationPanel;
